version: '3.8'

services:
  autoBN:
    build:
      context: ./  # Dockerfile 所在目录
      dockerfile: Dockerfile  # 可省略，如果就是默认名字

    image: autobn:latest
    container_name: autoBN
    restart: always
    volumes:
      - autoBN_data:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - shared-network
    environment:
      - TZ=Asia/Shanghai  # 设置为上海时区，可根据需求修改

networks:
  shared-network:
    external: true
    name: deploy_wechatpadpro-network  # 关键：使用项目A创建的网络全名

volumes:
  autoBN_data:
