[project]
name = "pythonproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "akshare>=1.17.85",
    "apscheduler>=3.11.1",
    "baostock>=0.8.9",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pyrogram>=2.0.106",
    "requests>=2.32.5",
    "web3>=7.14.0",
    "eth-account>=0.12.0",
    "pydantic>=2.12.4",
    "binance-sdk-derivatives-trading-portfolio-margin>=5.2.0",
    "binance-sdk-derivatives-trading-usds-futures>=9.0.0",
]
