# Generated by Django 4.1.7 on 2023-03-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
