# Generated by Django 4.1.7 on 2023-03-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('food_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
