# Generated by Django 4.1.3 on 2022-12-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SinfoM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=50, verbose_name="描述")),
                ("username", models.CharField(max_length=50, verbose_name="账号")),
                ("password", models.CharField(max_length=50, verbose_name="密码")),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="备注"
                    ),
                ),
            ],
            options={
                "verbose_name": "个人信息",
                "verbose_name_plural": "个人信息",
                "db_table": "self_info",
            },
        ),
    ]
