# Generated by Django 4.1.3 on 2022-12-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myAPP", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("article_id", models.AutoField(primary_key=True, serialize=False)),
                ("article_title", models.TextField()),
                ("article_abstract", models.TextField()),
                ("article_content", models.TextField()),
                ("article_data", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="SinfoM",
        ),
    ]
