# Generated by Django 4.1.3 on 2022-12-17 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myAPP", "0002_article_delete_sinfom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="article_abstract",
        ),
        migrations.RemoveField(
            model_name="article",
            name="article_content",
        ),
    ]
