# Generated by Django 4.1.3 on 2022-12-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myAPP", "0004_article_article_abstract"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dm", models.TextField()),
                ("jc", models.TextField()),
                ("zf", models.FloatField()),
                ("xj", models.FloatField()),
                ("data", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Article",
        ),
    ]
