# Generated by Django 4.1.3 on 2022-12-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myAPP", "0005_stock_delete_article"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Stock",
            new_name="Stocks",
        ),
    ]
