# Generated by Django 4.1.3 on 2022-12-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myAPP", "0006_rename_stock_stocks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stocks",
            old_name="zf",
            new_name="changeRatio",
        ),
        migrations.RenameField(
            model_name="stocks",
            old_name="dm",
            new_name="code",
        ),
        migrations.RenameField(
            model_name="stocks",
            old_name="xj",
            new_name="latest",
        ),
        migrations.RenameField(
            model_name="stocks",
            old_name="jc",
            new_name="stock",
        ),
    ]
