# Generated by Django 4.1.3 on 2022-12-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myAPP", "0009_rename_ths_up_and_down_status_stock_stocks_upperlimit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocks",
            name="upperLimit",
            field=models.FloatField(),
        ),
    ]
