# Generated by Django 4.1.3 on 2022-12-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myAPP", "0010_alter_stocks_upperlimit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degen", models.TextField()),
                ("project", models.TextField()),
                ("description", models.TextField()),
                ("created_at", models.TextField()),
                ("public_metrics", models.TextField()),
                ("profile_image_url", models.TextField()),
                ("degen_followers", models.TextField()),
                ("data", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
