# Generated by Django 4.1.3 on 2022-12-18 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myAPP", "0011_projects"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projects",
            old_name="data",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="stocks",
            old_name="data",
            new_name="date",
        ),
    ]
