# Generated by Django 3.2.5 on 2023-05-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alphainfo',
            name='alpha_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alphainfo',
            name='alpha_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alphainfo',
            name='tweet_alpha',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alphainfo',
            name='tweet_gpt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alphainfo',
            name='tweet_media',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alphainfo',
            name='tweet_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alphainfo',
            name='tweet_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alphainfo',
            name='tweet_user',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alphainfo',
            name='user_thumb',
            field=models.TextField(blank=True, null=True),
        ),
    ]
