# Generated by Django 3.2.5 on 2023-05-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphaApp', '0002_auto_20230507_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='Bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='Created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='DiscoveryTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='FollowedToday',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='Followers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
