# Generated by Django 3.2.5 on 2023-05-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphaApp', '0004_auto_20230519_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='callerinfo',
            name='tweet_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
