# Generated by Django 3.2.5 on 2023-05-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alphaApp', '0005_callerinfo_tweet_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectInfo',
            new_name='AlphaInfo',
        ),
    ]
