# Generated by Django 4.0 on 2023-05-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alphaApp', '0006_rename_projectinfo_alphainfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callerinfo',
            old_name='tweet_gpt',
            new_name='tweet_ai',
        ),
        migrations.RenameField(
            model_name='launchinfo',
            old_name='tweet_gpt',
            new_name='tweet_ai',
        ),
    ]
