# Generated by Django 4.0 on 2023-05-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphaApp', '0007_rename_tweet_gpt_callerinfo_tweet_ai_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callerinfo',
            old_name='alpha_time',
            new_name='tweet_tag',
        ),
        migrations.RenameField(
            model_name='launchinfo',
            old_name='alpha_time',
            new_name='tweet_tag',
        ),
        migrations.AddField(
            model_name='callerinfo',
            name='alpha_thumb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launchinfo',
            name='alpha_thumb',
            field=models.TextField(blank=True, null=True),
        ),
    ]
