# Generated by Django 4.0 on 2023-06-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphaApp', '0008_rename_alpha_time_callerinfo_tweet_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchinfo',
            name='list_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
