# Generated by Django 4.0 on 2023-06-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphaApp', '0009_launchinfo_list_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='callerinfo',
            name='list_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
