# Generated by Django 4.0 on 2023-06-30 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alphaApp', '0010_callerinfo_list_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callerinfo',
            old_name='list_name',
            new_name='list_account',
        ),
        migrations.RenameField(
            model_name='launchinfo',
            old_name='list_name',
            new_name='list_account',
        ),
    ]
