"""
Django settings for vxcxDJ project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w3gzw&**zkmphpka@1nfl^hap6r0a+lhi@u1dvg11ofayz)$%2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user.apps.UserConfig',
    'templatetags.UrlManager',
    'index.apps.IndexConfig',
    'account.apps.AccountConfig',
    'templatetags.libs.user.UserService',
    'pure_pagination',
    'api.apps.ApiConfig',
    'member.apps.MemberConfig',
    'apifood.apps.FoodConfig',
    'apimember.apps.ApimemberConfig',
    'upload.apps.UploadConfig',
    'food.apps.FoodConfig',
    'cart.apps.CartConfig',
    'order.apps.OrderConfig',
    'my.apps.MyConfig',
    'finance.apps.FinanceConfig',
    'statt.apps.StattConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vxcxDJ.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            # 写入libraries，格式为：<"过滤器名称": "位置">
            'libraries': {
                "buildStaticUrl": "templatetags.UrlManager",
                "buildUrl": "templatetags.UrlManager",
                "buildImageUrl":"templatetags.UrlManager",
                "get_item":"templatetags.UrlManager"
            },
        },
    },
]

WSGI_APPLICATION = 'vxcxDJ.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'order_db',
        'USER':'root',
        'PASSWORD':'yanlq2016',
        "HOST":'127.0.0.1',
        "PORT":'3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
REALEASE_VERSION = '20230209001'
AUTH_COOKIE_NAME='mooc_food'
AUTH_USER_MODEL = 'user.IfUser'
# setting.py 中  全局配置:没有登入跳转到指定的页面
LOGIN_URL = 'http://127.0.0.1:8000/user/login'
# 分页配置
PAGINATION_SETTINGS = {
    'PAGE_RANGE_DISPLAYED': 5,
    'MARGIN_PAGES_DISPLAYED': 2,
    'SHOW_FIRST_PAGE_WHEN_INVALID': True,
}
UPLOAD = {
    'ext':[ 'jpg','gif','bmp','jpeg','png' ],
    'prefix_path':'/static/upload/',
    'prefix_url':'/static/upload/'
}
APP = {
    'domain':'http://127.0.0.1:8000'
}
STATUS_MAPPING = {
    "1":"正常",
    "0":"已删除"
}
MINA_APP = {
    'appid' : 'wx024268fffe7368d2',
    'appkey' : '1ed17c6f10d03781e50a8c543dde4103'
}
# BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, os.path.join(BASE_DIR, 'api'))
PAY_STATUS_DISPLAY_MAPPING = {
    "0":"订单关闭",
    "1":"支付成功",
    "-8":"待支付",
    "-7":"待发货",
    "-6":"待确认",
    "-5":"待评价"
}