# Generated by Django 4.1.7 on 2023-03-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.TextField()),
                ('member_id', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('yun_price', models.FloatField()),
                ('pay_price', models.FloatField()),
                ('pay_sn', models.TextField()),
                ('prepay_id', models.TextField()),
                ('note', models.TextField()),
                ('status', models.IntegerField()),
                ('express_status', models.IntegerField()),
                ('express_address_id', models.IntegerField()),
                ('express_info', models.IntegerField()),
                ('comment_status', models.IntegerField()),
                ('pay_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayOrderCallbackDatum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_order_id', models.IntegerField()),
                ('pay_data', models.TextField()),
                ('refund_data', models.TextField()),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_order_id', models.IntegerField()),
                ('member_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('food_id', models.IntegerField()),
                ('note', models.TextField()),
                ('status', models.IntegerField()),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
