# Generated by Django 4.1.7 on 2023-03-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_payorder_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payorderitem',
            name='pay_order_id',
            field=models.IntegerField(default=1),
        ),
    ]
