# Generated by Django 4.1.7 on 2023-03-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_payorderitem_pay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payordercallbackdatum',
            name='pay_order_id',
            field=models.IntegerField(default=1),
        ),
    ]
