# Generated by Django 4.1.7 on 2023-03-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_payordercallbackdatum_pay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payorderitem',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
