# Generated by Django 2.2.28 on 2023-05-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('open_id', models.TextField(primary_key=True, serialize=False)),
                ('user_phone', models.TextField()),
                ('user_balance', models.IntegerField()),
                ('user_history', models.TextField()),
                ('user_ts', models.TextField()),
            ],
        ),
    ]
