# Generated by Django 4.0 on 2023-06-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishtarApp', '0002_auto_20230507_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
