# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayload.proto\".\n\x05Root2\x12\x16\n\x02\x66\x31\x18\x01 \x01(\x0b\x32\x07.Inner1R\x01\x31\x12\r\n\x02\x66\x32\x18\x02 \x01(\x05R\x01\x32\"\x80\x01\n\x06Inner1\x12\r\n\x02\x66\x31\x18\x01 \x01(\tR\x01\x31\x12\r\n\x02\x66\x32\x18\x02 \x01(\tR\x01\x32\x12\x1c\n\x02\x66\x34\x18\x04 \x01(\x0b\x32\r.Inner1Inner4R\x01\x34\x12\r\n\x02\x66\x35\x18\x05 \x01(\x05R\x01\x35\x12\r\n\x02\x66\x36\x18\x06 \x01(\x05R\x01\x36\x12\r\n\x02\x66\x38\x18\x08 \x01(\tR\x01\x38\x12\r\n\x02\x66\x39\x18\t \x01(\x05R\x01\x39\",\n\x0cInner1Inner4\x12\r\n\x02\x66\x31\x18\x01 \x01(\tR\x01\x31\x12\r\n\x02\x66\x32\x18\x02 \x01(\tR\x01\x32\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payload_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROOT2']._serialized_start=17
  _globals['_ROOT2']._serialized_end=63
  _globals['_INNER1']._serialized_start=66
  _globals['_INNER1']._serialized_end=194
  _globals['_INNER1INNER4']._serialized_start=196
  _globals['_INNER1INNER4']._serialized_end=240
# @@protoc_insertion_point(module_scope)
